spring:
    application:
        name: springboot-api-document
    servlet:
        multipart:
            location: /var/lib/upload
            max-file-size: 50MB

    # DB Connection 
    datasource:
        hikari:
            jdbc-url: jdbc:log4jdbc:postgresql://{db-url}/api
            driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
            username: {db-username}
            password: {db-password}
            maximum-pool-size: 5
    